### ISSUE TITLE
Text editor issues with Persian

### ISSUE THREAD

**Issue by p0o** [ziaa/pelicanyFay#1]
Thanks for contributing this project. I have the problem of writing Persian in text editors. Three of the text editors I use doesn't support it well so I can't write Markdown for RTL properly.

Do you have any suggestions? Preferably something for Mac or browsers.

**Comment by ziaa** [comment]
@p0o 
I'm using [RTL Markdown Editor](http://dariubs.github.io/rtlmd/). It's awesome! Give it a try!

**Comment by p0o** [comment]
Thank you @ziaa that's what I was looking for. Cheers
